# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default
#  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: VaultReadKV@5
  inputs:
    strAuthType: 'clientToken'
    strUrl: 'https://web.ciphertrustmanager.local/akeyless-api'
    ignoreCertificateChecks: true
    useProxy: 'none'
    strToken: 'accessid:p-20fdqvcnw5cuam..access_key:N8ELackgObo8eOL6kB2SASJdSJlZhKrkdhVCFu7kx6c='
    strKVEnginePath: '/MySecret1'
    kvVersion: 'v1'
    strPrefixType: 'custom'
    replaceCR: false